name: sonarr
services:
    sonarr:
        environment:
            PGID: $PGID
            PUID: $PUID
            TZ: $TZ
        image: linuxserver/sonarr:latest
        mem_reservation: "268435456"
        network_mode: bridge
        ports:
            - target: 8989
              published: "8989"
              protocol: tcp
        restart: unless-stopped
        volumes:
            - type: bind
              source: /DATA/AppData/$AppID/config
              target: /config
            - type: bind
              source: /DATA/Media/TV Shows
              target: /tv
            - type: bind
              source: /DATA/Downloads
              target: /downloads
        x-casaos:
            author: CasaOS Team
            category: Media
            container:
                envs:
                    - configurable: "no"
                      container: TZ
                      description:
                        en_US: TimeZone
                    - configurable: "no"
                      container: PUID
                      description:
                        en_US: Run Sonarr as specified uid.
                    - configurable: "no"
                      container: PGID
                      description:
                        en_US: Run Sonarr as specified gid.
                index: /
                port_map: "8989"
                ports:
                    - configurable: advanced
                      container: "8989"
                      description:
                        en_US: WebUI HTTP Port
                      protocol: tcp
                shell: bash
                volumes:
                    - configurable: "no"
                      container: /config
                      description:
                        en_US: Sonarr config directory.
                    - configurable: advanced
                      container: /tv
                      description:
                        en_US: Sonarr tv directory.
                    - configurable: advanced
                      container: /downloads
                      description:
                        en_US: Sonarr downloads directory.
            description:
                en_US: Sonarr is a PVR for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new episodes of your favorite shows and will grab, sort and rename them. It can also be configured to automatically upgrade the quality of files already downloaded when a better quality format becomes available.
            developer: Sonarr
            icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Sonarr/icon.png
            screenshot_link:
                - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Sonarr/screenshot-1.jpg
                - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Sonarr/screenshot-2.jpg
                - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Sonarr/screenshot-3.jpg
                - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Sonarr/screenshot-4.jpg
            tagline:
                en_US: The PVR for Usenet and BitTorrent users
            thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Radarr/thumbnail.jpg
            tips: {}
            title:
                en_US: Sonarr
x-casaos:
    architectures:
        - amd64
        - arm64
    main_app: sonarr
    version: latest
