name: octobercms
services:
  main_app:
    cpu_shares: 10
    image: octobercms/october-dev:latest
    labels:
      icon: https://icon.casaos.io/main/all/october-dev.png
    ports:
      - target: 80
        published: "8080"
        protocol: tcp
      - target: 3306
        published: "3306"
        protocol: tcp
    restart: unless-stopped
    x-casaos:
      envs:
        - container: DB_TYPE
          description:
            en_us: Database type (sqlite or mysql)
      ports:
        - container: "80"
          description:
            en_us: Web UI Port
      volumes:
        - container: /var/www/html
          description:
            en_us: October CMS installation folder
    network_mode: bridge
    privileged: false
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/www
        target: /var/www/html
x-casaos:
  architectures:
    - amd64
    - arm64
  main: main_app
  author: CasaOS Community
  category: Content Management
  hostname: ""
  icon: https://icon.casaos.io/main/all/october-dev.png
  index: /backend
  is_uncontrolled: false
  port_map: "8080"
  scheme: http
  store_app_id: octobercms
  title:
    en_us: October CMS
  tagline:
    en_us: The Laravel-based CMS for creators
  description:
    en_us: October CMS is a free, open-source, self-hosted CMS platform based on the Laravel PHP framework. It is designed to be simple, flexible, and developer-friendly.
  developer: October CMS
  screenshot_link: []
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/OctoberCMS/thumbnail.png
