name: wg-easy
services:
  wg-easy:
    image: weejewel/wg-easy:7
    restart: unless-stopped
    network_mode: bridge
    environment:
      PASSWORD: 'casaos'
      WG_HOST: 'casaos.local'
      WG_PORT: '51820'
      WG_DEFAULT_DNS: '1.1.1.1'
    x-casaos:
      volumes:
        - container: /etc/wireguard
          description:
            en_us: Contains device VPN config files.
      ports:
        - container: '51820'
          description:
            en_us: Wireguard VPN port
        - container: '51821'
          description:
            en_us: WEB UI port
    ports:
      - target: 51820
        published: "51820"
        protocol: udp
      - target: 51821
        published: "51821"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/wireguard
        target: /etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    container_name: wg-easy
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: wg-easy
  description:
    en_us: WEB UI to manage WireGuard VPN.
    zh_cn: ÁÆ°ÁêÜ WireGuard VPN ÁöÑ WEB UI„ÄÇ
    de_de: WEB UI zur Verwaltung von WireGuard VPN.
    es_es: WEB UI para gestionar WireGuard VPN.
    fr_fr: WEB UI pour g√©rer WireGuard VPN.
    hu_hu: WEB felhaszn√°l√≥i fel√ºlet a WireGuard VPN kezel√©s√©hez.
    it_it: Interfaccia WEB per la gestione di WireGuard VPN.
    ru_ru: WEB-–∏–Ω—Ç–µ—Ä—Ñ–µ–π—Å –¥–ª—è —É–ø—Ä–∞–≤–ª–µ–Ω–∏—è WireGuard VPN.
    pl_pl: WEB UI do zarzƒÖdzania WireGuard VPN.
    pt_br: WEB UI para gerenciar o WireGuard VPN.
    sv_se: WEB UI f√∂r att hantera WireGuard VPN.
    uk_ua: WEB —ñ–Ω—Ç–µ—Ä—Ñ–µ–π—Å –¥–ª—è –∫–µ—Ä—É–≤–∞–Ω–Ω—è WireGuard VPN.
  tagline:
    en_us: You have found the easiest way to install & manage WireGuard on any Linux host!
    zh_cn: ÊÇ®Â∑≤ÁªèÊâæÂà∞‰∫ÜÂú®‰ªª‰Ωï Linux ‰∏ªÊú∫‰∏äÂÆâË£ÖÂíåÁÆ°ÁêÜ WireGuard ÁöÑÊúÄÁÆÄÂçïÊñπÊ≥ïÔºÅ
    de_de: Sie haben den einfachsten Weg gefunden, WireGuard auf jedem Linux-Host zu installieren und zu verwalten!
    es_es: Ha encontrado la forma m√°s sencilla de instalar y gestionar WireGuard en cualquier host Linux.
    fr_fr: Vous avez trouv√© le moyen le plus simple d'installer et de g√©rer WireGuard sur n'importe quel h√¥te Linux !
    hu_hu: Megtal√°lta a WireGuard telep√≠t√©s√©nek √©s kezel√©s√©nek legegyszer≈±bb m√≥dj√°t b√°rmely Linux hoszton!
    it_it: Avete trovato il modo pi√π semplice per installare e gestire WireGuard su qualsiasi host Linux!
    ru_ru: –í—ã –Ω–∞—à–ª–∏ —Å–∞–º—ã–π –ø—Ä–æ—Å—Ç–æ–π —Å–ø–æ—Å–æ–± —É—Å—Ç–∞–Ω–æ–≤–∫–∏ –∏ —É–ø—Ä–∞–≤–ª–µ–Ω–∏—è WireGuard –Ω–∞ –ª—é–±–æ–º Linux-—Ö–æ—Å—Ç–µ!
    pl_pl: Znalaz≈Çe≈õ naj≈Çatwiejszy spos√≥b instalacji i zarzƒÖdzania WireGuard na dowolnym ho≈õcie z systemem Linux!
    pt_br: Voc√™ encontrou a maneira mais f√°cil de instalar e gerenciar o WireGuard em qualquer host Linux!
    sv_se: Du har hittat det enklaste s√§ttet att installera och hantera WireGuard p√• en Linux-v√§rd!
    uk_ua: –í–∏ –∑–Ω–∞–π—à–ª–∏ –Ω–∞–π–ø—Ä–æ—Å—Ç—ñ—à–∏–π —Å–ø–æ—Å—ñ–± –≤—Å—Ç–∞–Ω–æ–≤–∏—Ç–∏ WireGuard —Ç–∞ –∫–µ—Ä—É–≤–∞—Ç–∏ –Ω–∏–º –Ω–∞ –±—É–¥—å-—è–∫–æ–º—É –∫–æ–º–ø'—é—Ç–µ—Ä—ñ –∑ Linux!
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/WireGuardEasy/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/WireGuardEasy/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/WireGuardEasy/screenshot-3.png
  developer: WeejeWel
  author: Sawy
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/WireGuardEasy/icon.png
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/WireGuardEasy/icon.png
  category: Network
  tips:
    before_install:
      en_us: |
        üîß Settings

        Default password: `casaos`

        ‚ö†Ô∏è Warning!

        You need to change at least change the mandatory parameter `WG_HOST` for this app to work properly.
        It's value has to be a domain (or an IP address) that points to this server (accesible from WAN).

        Same applies to the `WG_PORT` parameter. Change it to the port accessible from outside your LAN if it differs from the default 51820.
  title:
    en_us: WireGuard Easy
  port_map: '51821'
