name: sickchill
services:
  sickchill:
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/London
    image: linuxserver/sickchill:2023.1.2
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 8081
        published: "8081"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/sickchill/config
        target: /config
      - type: bind
        source: /DATA/Downloads
        target: /downloads
      - type: bind
        source: /DATA/Media/TV Shows
        target: /tv
    x-casaos:
      author: CasaOS Team
      category: Media
      container:
        envs:
          - configurable: "no"
            container: PUID
            description:
              en_US: ""
          - configurable: "no"
            container: PGID
            description:
              en_US: ""
          - configurable: "no"
            container: TZ
            description:
              en_US: ""
        port_map: "8081"
        ports:
          - configurable: "no"
            container: "8081"
            description:
              en_US: ""

        shell: sh
        volumes:
          - configurable: "no"
            container: /config
            description:
              en_US: ""
          - configurable: "no"
            container: /downloads
            description:
              en_US: ""
          - configurable: "no"
            container: /tv
            description:
              en_US: ""
      description:
        en_US: 'SickChill is an automatic Video Library Manager for TV Shows. It watches for new episodes of your favorite shows, and when they are posted it does its magic: automatic torrent/nzb searching, downloading, and processing at the qualities you want.'
      developer: Sickchill Team
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Sickchill/icon.png
      screenshot_link:
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Sickchill/screenshot-1.png
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Sickchill/screenshot-2.png
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Sickchill/screenshot-3.png
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Sickchill/screenshot-4.png
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Sickchill/screenshot-5.png
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Sickchill/screenshot-6.png
      tagline:
        en_US: Automatic video library manager for TV Shows
      thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Readarr/thumbnail.png
      tips: {}
      title:
        en_US: Sickchill
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main_app: sickchill
