version: "3.7"
name: cloudbeaver
services:
  cloudbeaver:
    container_name: cloudbeaver
    deploy:
      resources:
        limits:
          memory: 256M
    image: dbeaver/cloudbeaver:23.2.4
    ports:
      - target: 8978
        published: "5216"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/workspace
        target: /opt/cloudbeaver/workspace
    network_mode: bridge
    privileged: false
    x-casaos:
      ports:
        - container: "8978"
          description:
            en_us: WebUI HTTP Port
          protocol: tcp   
      volumes:
        - container: /opt/cloudbeaver/workspace
          description:
            en_us: Workspace directory.

x-casaos:
  architectures:
    - amd64
    - arm64
  main: cloudbeaver
  author: joaobosconff
  category: Developer
  description:
    en_us: CloudBeaver is a web-based database GUI tool which provides rich web interface. You can use it to manage PostgreSQL, MySQL, MariaDB, SQL Server, Oracle, DB2, Firebird, H2, Trino.
    pt_br: CloudBeaver é uma ferramenta GUI de banco de dados baseada na web que oferece uma interface web abrangente. Você pode usá-lo para gerenciar PostgreSQL, MySQL, MariaDB, SQL Server, Oracle, DB2, Firebird, H2 e Trino.
  developer: dbeaver
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/CloudBeaver/icon.png
  screenshot_link:
  - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/CloudBeaver/screenshot-1.png
  - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/CloudBeaver/screenshot-2.png
  - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/CloudBeaver/screenshot-3.png
  tagline:
    en_us: Cloud Database Manager.
    pt_br: Administrador de Banco de Dados na Nuvem.
  title:
    en_us: CloudBeaver
    pt_br: CloudBeaver
  index: /
  port_map: "8978"
