name: adguard-home
services:
    adguard-home:
        image: adguard/adguardhome:v0.107.5
        mem_reservation: "67108864"
        network_mode: bridge
        ports:
            - target: 53
              published: "53"
              protocol: tcp
            - target: 53
              published: "53"
              protocol: udp
            - target: 3000
              published: "3000"
              protocol: tcp
            - target: 853
              published: "853"
              protocol: tcp
            - target: 784
              published: "784"
              protocol: udp
        restart: unless-stopped
        volumes:
            - type: bind
              source: /DATA/AppData/$AppID/opt/adguardhome/work
              target: /opt/adguardhome/work
            - type: bind
              source: /DATA/AppData/$AppID/opt/adguardhome/conf
              target: /opt/adguardhome/conf
        x-casaos:
            author: CasaOS Team
            category: Network
            container:
                index: /
                port_map: "3000"
                ports:
                    - configurable: "no"
                      container: "53"
                      description:
                        en_US: ""
                      protocol: tcp
                    - configurable: "no"
                      container: "53"
                      description:
                        en_US: ""
                      protocol: udp
                    - configurable: "no"
                      container: "3000"
                      description:
                        en_US: ""
                      protocol: tcp
                    - configurable: "no"
                      container: "853"
                      description:
                        en_US: ""
                      protocol: tcp
                    - configurable: "no"
                      container: "784"
                      description:
                        en_US: ""
                      protocol: udp
                shell: sh
                volumes:
                    - configurable: "no"
                      container: /opt/adguardhome/work
                      description:
                        en_US: ""
                    - configurable: "no"
                      container: /opt/adguardhome/conf
                      description:
                        en_US: ""
            description:
                en_US: AdGuard Home is a network-wide software for blocking ads and tracking. After you set it up, it'll cover all your home devices, and you won't need any client-side software for that. Learn more on our official Github repository.
            developer: AdguardTeam
            icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/icon.png
            screenshot_link:
                - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/screenshot-1.png
                - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/screenshot-2.png
                - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/screenshot-3.png
            tagline:
                en_US: 'Network-wide ads & trackers blocking DNS server '
            thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/thumbnail.png
            tips: {}
            title:
                en_US: AdGuard Home
x-casaos:
    architectures:
        - "386"
        - amd64
        - arm
        - arm64
        - ppc64le
    main_app: adguard-home
