name: adguard-home
services:
  adguard-home:
    image: adguard/adguardhome:v0.107.55
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 53
        published: "531"
        protocol: tcp
      - target: 53
        published: "531"
        protocol: udp
      - target: 3000
        published: "3001"
        protocol: tcp
      - target: 853
        published: "853"
        protocol: tcp
      - target: 784
        published: "784"
        protocol: udp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/opt/adguardhome/work
        target: /opt/adguardhome/work
      - type: bind
        source: /DATA/AppData/$AppID/opt/adguardhome/conf
        target: /opt/adguardhome/conf
    x-casaos:
      ports:
        - container: "53"
          description:
            en_us: ""
        - container: "53"
          description:
            en_us: ""
        - container: "3000"
          description:
            en_us: ""
        - container: "853"
          description:
            en_us: ""
        - container: "784"
          description:
            en_us: ""

      volumes:
        - container: /opt/adguardhome/work
          description:
            en_us: ""
        - container: /opt/adguardhome/conf
          description:
            en_us: ""
    container_name: adguard-home
x-casaos:
  architectures:
    - "386"
    - amd64
    - arm
    - arm64
    - ppc64le
  main: adguard-home
  author: CasaOS Team
  category: Network
  description:
    en_us: |
      Difference from Traditional Ad Blockers. Unlike traditional ad-blocking plugins that work only on individual devices, AdGuard Home offers a network-wide solution. By setting it up, you can block ads and trackers across all your home devices without needing to install any additional software on each device. This means comprehensive protection with minimal effort.
      
      How AdGuard Home Works and How to Use It. AdGuard Home functions as a DNS server that reroutes tracking domains to a "black hole," effectively preventing your devices from connecting to these servers. This blocks ads and trackers not only on your computer but also on your smartphone and smart home devices. To start using AdGuard Home, deploy it on your device, then change the DNS address assigned by DHCP on your router to the IP address of your AdGuard Home server.
      
      Benefits of Deploying AdGuard Home on Zima Private Cloud. Deploying AdGuard Home on a Zima device simplifies network-wide ad and tracker blocking, providing a seamless and secure browsing experience for all your home devices. With Zima, you gain the flexibility to monitor network activity and create custom filtering rules tailored to your needs.
    zh_cn: | 
      与传统广告拦截器的不同之处。不同于仅在单个设备上工作的传统广告拦截插件，AdGuard Home 提供了一种网络范围的解决方案。通过设置它，您可以在所有家庭设备上屏蔽广告和跟踪器，而无需在每个设备上安装额外的软件。这意味着以最少的努力获得全面的保护。

      AdGuard Home 的工作原理及使用方法。AdGuard Home 作为一个 DNS 服务器，通过将跟踪域重定向到“黑洞”来有效地防止您的设备连接到这些服务器。这不仅能在您的计算机上屏蔽广告和跟踪器，还能在您的智能手机和智能家居设备上实现。要开始使用 AdGuard Home，请将其部署在您的设备上，然后将路由器通过 DHCP 分配的 DNS 地址更改为 AdGuard Home 服务器的 IP 地址。

      在 Zima 私有云上部署 AdGuard Home 的好处。在 Zima 设备上部署 AdGuard Home 简化了网络范围内的广告和跟踪器拦截，为您所有的家庭设备提供无缝且安全的浏览体验。借助 Zima，您可以灵活地监控网络活动并创建适合您需求的自定义过滤规则。
    ar_sa: AdGuard Home هو برنامج شبكة واسعة لمنع الإعلانات والتتبع. بعد إعداده، سيغطي جميع أجهزة منزلك، ولن تحتاج إلى أي برنامج جانبي للعميل. تعرف على المزيد من مستودعنا الرسمي على Github.
    de_de: AdGuard Home ist eine Netzwerksoftware zum Blockieren von Werbung und Tracking. Nachdem Sie es eingerichtet haben, deckt es alle Ihre Heimgeräte ab und Sie benötigen dafür keine Client-Software. Erfahren Sie mehr in unserem offiziellen Github-Repository.
    es_es: AdGuard Home es un software de red para bloquear anuncios y rastreo. Después de configurarlo, cubrirá todos sus dispositivos en el hogar y no necesitará ningún software cliente para ello. Obtenga más información en nuestro repositorio oficial de Github.
    fr_fr: AdGuard Home est un logiciel réseau pour bloquer les publicités et le suivi. Une fois configuré, il couvrira tous vos appareils domestiques et vous n'aurez pas besoin de logiciel client pour cela. En savoir plus sur notre référentiel officiel Github.
    hu_hu: Az AdGuard Home egy hálózati szintű szoftver a hirdetések és a követők blokkolására. Miután beállította, minden otthoni eszközét le fogja fedni, és erre nem lesz szüksége kliensoldali szoftverre sem. További információkért látogasson el hivatalos Github-tárolójába.
    it_it: AdGuard Home è un software a livello di rete per bloccare annunci e tracciamento. Dopo averlo configurato, coprirà tutti i tuoi dispositivi domestici e non avrai bisogno di alcun software client per questo. Ulteriori informazioni sul nostro repository ufficiale Github.
    ru_ru: AdGuard Home - это программное обеспечение для блокировки рекламы и отслеживания на уровне всей сети. После настройки оно будет покрывать все ваши домашние устройства, и вам не понадобится какое-либо клиентское программное обеспечение для этого. Узнайте больше на нашем официальном репозитории Github.
    pl_pl: AdGuard Home to oprogramowanie sieciowe do blokowania reklam i śledzenia. Po skonfigurowaniu obejmie wszystkie urządzenia domowe, a nie będzie potrzebny żaden oprogramowanie klienta. Dowiedz się więcej na naszym oficjalnym repozytorium Github.
    pt_br: O AdGuard Home é um software de rede para bloquear anúncios e rastreamento. Depois de configurá-lo, ele cobrirá todos os seus dispositivos domésticos e você não precisará de nenhum software cliente para isso. Saiba mais em nosso repositório oficial do Github.
    sv_se: AdGuard Home är ett nätverksprogram för att blockera annonser och spårning. Efter att du har konfigurerat det kommer det att täcka alla dina hemmamaskiner och du behöver inte någon klientprogramvara för det. Läs mer på vår officiella Github-repository.
    uk_ua: AdGuard Home - це програмне забезпечення для блокування реклами і відстеження на рівні всієї мережі. Після налаштування воно буде покривати всі ваші домашні пристрої, і вам не буде потрібно жодного клієнтського програмного забезпечення для цього. Дізнайтеся більше на нашому офіційному репозиторії Github.
  developer: AdguardTeam
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/screenshot-3.png
  tagline:
    en_us: Blocking ads & tracking Network-widly
    zh_cn: 在网络侧阻止广告和跟踪
    ar_sa: خادم DNS لمنع الإعلانات والمتتبعين على نطاق الشبكة
    de_de: Netzwerkweites Werbe- und Tracker-Blockierungs-DNS-Server
    es_es: Servidor DNS de bloqueo de anuncios y rastreadores a nivel de red
    fr_fr: Serveur DNS de blocage de publicités et de traqueurs sur tout le réseau
    hu_hu: Hálózati szintű hirdetések és követők blokkoló DNS szerver
    it_it: Server DNS di blocco annunci e tracciatori a livello di rete
    ru_ru: DNS-сервер блокировки рекламы и трекеров на уровне сети
    pl_pl: Serwer DNS blokujący reklamy i śledzenie na poziomie sieci
    pt_br: Servidor DNS de bloqueio de anúncios e rastreadores em nível de rede
    sv_se: Nätverksnivå DNS-server för att blockera annonser och spårare
    uk_ua: DNS-сервер блокування реклами та трекерів на рівні мережі
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/thumbnail.png
  tips: {}
  title:
    en_us: AdGuard Home
  index: /
  port_map: "3001"
