name: adguard-home
services:
  adguard-home:
    image: adguard/adguardhome:v0.107.5
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 53
        published: "53"
        protocol: tcp
      - target: 53
        published: "53"
        protocol: udp
      - target: 3000
        published: "3000"
        protocol: tcp
      - target: 853
        published: "853"
        protocol: tcp
      - target: 784
        published: "784"
        protocol: udp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/opt/adguardhome/work
        target: /opt/adguardhome/work
      - type: bind
        source: /DATA/AppData/$AppID/opt/adguardhome/conf
        target: /opt/adguardhome/conf
    x-casaos:
      author: CasaOS Team
      category: Network
      container:
        index: /
        port_map: "3000"
        ports:
          - container: "53"
            description:
              en_US: ""
          - container: "53"
            description:
              en_US: ""
          - container: "3000"
            description:
              en_US: ""
          - container: "853"
            description:
              en_US: ""
          - container: "784"
            description:
              en_US: ""

        volumes:
          - container: /opt/adguardhome/work
            description:
              en_US: ""
          - container: /opt/adguardhome/conf
            description:
              en_US: ""
      description:
        en_US: AdGuard Home is a network-wide software for blocking ads and tracking. After you set it up, it'll cover all your home devices, and you won't need any client-side software for that. Learn more on our official Github repository.
        zh_CN: AdGuard Home 是一个网络范围的软件，用于阻止广告和跟踪。设置完成后，它将覆盖您的所有家庭设备，您不需要任何客户端软件。在我们的官方Github存储库上了解更多信息。
      developer: AdguardTeam
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/icon.png
      screenshot_link:
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/screenshot-1.png
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/screenshot-2.png
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/screenshot-3.png
      tagline:
        en_US: Network-wide ads & trackers blocking DNS server
        zh_CN: 网络范围的广告和跟踪阻止DNS服务器
      thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/thumbnail.png
      tips: {}
      title:
        en_US: AdGuard Home
x-casaos:
  architectures:
    - "386"
    - amd64
    - arm
    - arm64
    - ppc64le
  main_app: adguard-home
