name: lidarr
services:
  lidarr:
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/London
    image: linuxserver/lidarr:1.0.2
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 8686
        published: "8686"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/lidarr/config
        target: /config
      - type: bind
        source: /DATA/Media/Music
        target: /music
      - type: bind
        source: /DATA/Downloads
        target: /downloads
    x-casaos:
      author: CasaOS Team
      category: Downloader
      container:
        envs:
          -
            container: PUID
            description:
              en_US: ""
          -
            container: PGID
            description:
              en_US: ""
          -
            container: TZ
            description:
              en_US: ""
        port_map: "8686"
        ports:
          -
            container: "8686"
            description:
              en_US: ""

        shell: sh
        volumes:
          -
            container: /config
            description:
              en_US: ""
          -
            container: /music
            description:
              en_US: ""
          -
            container: /downloads
            description:
              en_US: ""
      description:
        en_US: Lidarr is a music collection manager for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new albums from your favorite artists and will interface with clients and indexers to grab, sort, and rename them. It can also be configured to automatically upgrade the quality of existing files in the library when a better quality format becomes available.
      developer: lidarr Team
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Lidarr/icon.png
      screenshot_link:
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Lidarr/screenshot-1.png
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Lidarr/screenshot-2.png
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Lidarr/screenshot-3.png
      tagline:
        en_US: Music collection manager for Usenet and BitTorrent users
      thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Lidarr/thumbnail.png
      tips: {}
      title:
        en_US: Lidarr
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main_app: lidarr
