name: navidrome
services:
  navidrome:
    container_name: navidrome
    deploy:
      resources:
        reservations:
          memory: 1024M
    image: deluan/navidrome:0.50.1
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Navidrome/icon.png
    restart: unless-stopped
    ports:
      - target: 4533
        published: "4533"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /data
      - type: bind
        source: /DATA/Media/Music
        target: /music
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      TZ: $TZ
    network_mode: bridge
    privileged: false
    x-casaos:
      envs:
        - container: ND_SCANSCHEDULE
          description:
            en_us: Configure periodic scans using cron syntax.
            zh_cn: 使用cron语法配置定期扫描。
        - container: ND_LOGLEVEL
          description:
            en_us: Log level.
            zh_cn: 日志级别。
        - container: ND_SESSIONTIMEOUT
          description:
            en_us: How long Navidrome will wait before closing web ui idle sessions
            zh_cn: Navidrome在关闭Web UI空闲会话之前等待多长时间
        - container: ND_BASEURL
          description:
            en_us: 'Base URL (only the path part) to configure Navidrome behind a proxy (ex: /music)'
            zh_cn: 配置Navidrome在代理后面的基本URL（仅路径部分）（例如：/music）
        - container: TZ
          description:
            en_us: TimeZone
            zh_cn: 时区
      volumes:
        - container: /data
          description:
            en_us: AppData Data File
            zh_cn: AppData数据文件
        - container: /music
          description:
            en_us: Music folder
            zh_cn: 音乐文件夹
      ports:
        - container: '4533'
          description:
            en_us: WebUI Port for Navidrome
            zh_cn: Navidrome的WebUI端口

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  author: "The Navidrome Authors"
  category: "Media"
  description:
    en_us: Navidrome is an open source web-based music collection server and streamer. It gives you freedom to listen to your music collection from any browser or mobile device. It's like your personal Spotify!
    zh_cn: Navidrome是一个开源的基于Web的音乐收藏服务器和流媒体服务器。它让您可以在任何浏览器或移动设备上自由收听音乐收藏。就像您个人的Spotify一样！
  tagline:
    en_us: Music Collection and Streaming Server
    zh_cn: 音乐收藏和流媒体服务器
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Navidrome/icon.png
  index: /
  main: navidrome
  port_map: "4533"
  scheme: http
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Navidrome/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Navidrome/screenshot-2.png
  store_app_id: navidrome
  title:
    en_us: Navidrome