name: threadfin
services:
  threadfin:
    image: fyb3roptik/threadfin:latest
    restart: unless-stopped
    environment:
      - THREADFIN_BRANCH=main
      - THREADFIN_DEBUG=0
    x-casaos:
      volumes:
        - container: /home/threadfin/conf/data
          description:
            en_us: Data
        - container: /home/threadfin/conf/backup
          description:
            en_us: Backup
      envs:
        - container: THREADFIN_BRANCH
          description:
            en_us: "Set Threadfin git branch [ main, beta, dev ] Default: beta"
        - container: THREADFIN_DEBUG
          description:
            en_us: "Set Threadfin debug level [ 0-3 ] Default: 0=OFF"
      ports:
        - container: "34400"
          description:
            en_us: Port to access the application's GUI via the web interface.
    ports:
      - target: 34400
        published: "34400"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/threadfin/config
        target: /home/threadfin/conf/data
      - type: bind
        source: /DATA/AppData/threadfin/backup
        target: /home/threadfin/conf/backup
    container_name: threadfin
x-casaos:
  architectures:
    - amd64
    - arm64
  main: threadfin
  description:
    en_us: M3U Proxy for Plex DVR and Emby/Jellyfin Live TV. Based on xTeVe.
  developer: jdownloader
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Threadfin/icon.png
  author: Fabio Tea
  category: Utility
  index: /web/
  port_map: "34400"
  scheme: http
  store_app_id: threadfin
  title:
    en_us: Threadfin
