name: xiaomi-album-syncer

services:
  xiaomi-album-syncer:
    image: coolfan1024/xiaomi-album-syncer:0.8.2
    container_name: xiaomi-album-syncer
    ports:
      - target: 8080
        published: ${WEBUI_PORT}
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/download
        target: /app/download
      - type: bind
        source: /DATA/AppData/$AppID/db
        target: /app/db
    restart: unless-stopped

x-casaos:
    architectures:
        - amd64
        - arm64
    main: xiaomi-album-syncer
    author: github.com/coooolfan
    category: Backup
    description:
        en_us: |
          Xiaomi Album Syncer is a tool to sync photos from Xiaomi cloud to your local computer.
          - ğŸ“¸ Download all photos in the specified album
          - â­ï¸ Skip already downloaded photos
          - ğŸ”„ Automatically refresh Cookie
          - â° Support timed tasks
          - ğŸ“¥ Support incremental download (super fast)
          - ğŸ—‚ï¸ Support storing photos by album
          - ğŸŒ Friendly Web UI
          - ğŸ“… Fill Exif time information for photos and videos
          - ğŸ“… Fill file system time for photos and videos
        zh_cn: |
          å°ç±³ç›¸å†ŒåŒæ­¥å™¨æ˜¯ä¸€æ¬¾å°†å°ç±³äº‘ç›¸å†ŒåŒæ­¥åˆ°æœ¬åœ°ç”µè„‘çš„å·¥å…·ï¼Œæ”¯æŒï¼š
          - ğŸ“¸ ä¸‹è½½æŒ‡å®šç›¸å†Œä¸­çš„æ‰€æœ‰ç…§ç‰‡
          - â­ï¸ è‡ªåŠ¨è·³è¿‡å·²ä¸‹è½½çš„ç…§ç‰‡
          - ğŸ”„ è‡ªåŠ¨åˆ·æ–° Cookie
          - â° æ”¯æŒå®šæ—¶ä»»åŠ¡
          - ğŸ“¥ æ”¯æŒå¢é‡ä¸‹è½½ï¼ˆè¶…å¿«ï¼‰
          - ğŸ—‚ï¸ æ”¯æŒæŒ‰ç›¸å†Œåˆ†ç±»å­˜å‚¨ç…§ç‰‡
          - ğŸŒ å‹å¥½çš„ Web UI
          - ğŸ“… å¡«å……ç…§ç‰‡å’Œè§†é¢‘çš„ Exif æ—¶é—´ä¿¡æ¯
          - ğŸ“… å¡«å……ç…§ç‰‡å’Œè§†é¢‘çš„æ–‡ä»¶ç³»ç»Ÿæ—¶é—´
    developer: github.com/coooolfan
    icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/XiaomiAlbumSyncer/icon.png
    tagline:
        en_us: Xiaomi Album Syncer is a tool to sync photos from Xiaomi cloud to your local computer.
        zh_cn: å°ç±³ç›¸å†ŒåŒæ­¥å™¨æ˜¯ä¸€æ¬¾å°†å°ç±³äº‘ç›¸å†ŒåŒæ­¥åˆ°æœ¬åœ°ç”µè„‘çš„å·¥å…·ã€‚
    thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/XiaomiAlbumSyncer/thumbnail.png
    screenshot_link:
      - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/XiaomiAlbumSyncer/screenshot-1.png
    title:
        en_us: Xiaomi Album Syncer
        zh_cn: å°ç±³ç›¸å†ŒåŒæ­¥å™¨
    index: /
    port_map: ${WEBUI_PORT}