name: xiaomi-album-syncer

services:
  xiaomi-album-syncer:
    image: coolfan1024/xiaomi-album-syncer:0.8.2
    container_name: xiaomi-album-syncer
    ports:
      - target: 8080
        published: ${WEBUI_PORT}
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/download
        target: /app/download
      - type: bind
        source: /DATA/AppData/$AppID/db
        target: /app/db
    restart: unless-stopped

x-casaos:
    architectures:
        - amd64
        - arm64
    main: xiaomi-album-syncer
    author: github.com/coooolfan
    category: Backup
    description:
        en_us: Xiaomi Album Syncer is a tool to sync photos from Xiaomi cloud to your local computer.
        zh_cn: 小米相册同步器是一款将小米云相册同步到本地电脑的工具。
    developer: github.com/coooolfan
    icon: https://github.com/Coooolfan/CasaOS-AppStore/blob/feat/xiaomi-album-syncer/Apps/XiaomiAlbumSyncer/logo.png?raw=true
    tagline:
        en_us: Xiaomi Album Syncer is a tool to sync photos from Xiaomi cloud to your local computer.
        zh_cn: 小米相册同步器是一款将小米云相册同步到本地电脑的工具。
    thumbnail: https://github.com/Coooolfan/CasaOS-AppStore/blob/feat/xiaomi-album-syncer/Apps/XiaomiAlbumSyncer/thumbnail.png?raw=true
    screenshot_link:
      - https://github.com/Coooolfan/CasaOS-AppStore/blob/feat/xiaomi-album-syncer/Apps/XiaomiAlbumSyncer/screenshot-1.png?raw=true
    title:
        en_us: Xiaomi Album Syncer
        zh_cn: 小米相册同步器
    index: /
    port_map: ${WEBUI_PORT}