name: crafty
# Base file from https://gitlab.com/crafty-controller/crafty-4/-/blob/dev/docker/docker-compose.yml
version: "3"

services:
  crafty:
    container_name: crafty-container
    image: registry.gitlab.com/crafty-controller/crafty-4:4.3.2
    restart: always
    environment:
      - TZ=Etc/UTC
    ports:
      - "8110:8000" # HTTP
      - "8111:8443" # HTTPS
      - "8112:8123" # DYNMAP
      - "19132:19132/udp" # BEDROCK
      - "25500-25600:25500-25600" # MC SERVER PORT RANGE
    volumes:
      - /DATA/AppData/crafty/backups:/crafty/backups
      - /DATA/AppData/crafty/logs:/crafty/logs
      - /DATA/AppData/crafty/servers:/crafty/servers
      - /DATA/AppData/crafty/config:/crafty/app/config
      - /DATA/AppData/crafty/import:/crafty/import

    x-casaos:
      ports:
        - container: "8000"
          description:
            en_us: WebUI HTTP Port
            zh_cn: WebUI HTTP端口
          protocol: tcp

        - container: "19132"
          description:
            en_us: Minecraft Bedrock listening Port (UDP)
            zh_cn: Minecraft Bedrock监听端口 (UDP)
          protocol: udp

        - container: "25565"
          description:
            en_us: Minecraft listening Port (TCP)
            zh_cn: Minecraft监听端口 (TCP)
          protocol: tcp

        - container: "25566"
          description:
            en_us: Minecraft listening Port (TCP)
            zh_cn: Minecraft监听端口 (TCP)
          protocol: tcp

        - container: "25567"
          description:
            en_us: Minecraft listening Port (TCP)
            zh_cn: Minecraft监听端口 (TCP)
          protocol: tcp

        - container: "25568"
          description:
            en_us: Minecraft listening Port (TCP)
            zh_cn: Minecraft监听端口 (TCP)
          protocol: tcp

        - container: "25569"
          description:
            en_us: Minecraft listening Port (TCP)
            zh_cn: Minecraft监听端口 (TCP)
          protocol: tcp

        - container: "25570"
          description:
            en_us: Minecraft listening Port (TCP)
            zh_cn: Minecraft监听端口 (TCP)
          protocol: tcp

        - container: "25565"
          description:
            en_us: Minecraft listening Port (UDP)
            zh_cn: Minecraft监听端口 (UDP)
          protocol: udp

        - container: "25566"
          description:
            en_us: Minecraft listening Port (UDP)
            zh_cn: Minecraft监听端口 (UDP)
          protocol: udp

        - container: "25567"
          description:
            en_us: Minecraft listening Port (UDP)
            zh_cn: Minecraft监听端口 (UDP)
          protocol: udp

        - container: "25568"
          description:
            en_us: Minecraft listening Port (UDP)
            zh_cn: Minecraft监听端口 (UDP)
          protocol: udp

        - container: "25569"
          description:
            en_us: Minecraft listening Port (UDP)
            zh_cn: Minecraft监听端口 (UDP)
          protocol: udp

        - container: "25570"
          description:
            en_us: Minecraft listening Port (UDP)
            zh_cn: Minecraft监听端口 (UDP)
          protocol: udp
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: crafty
  author: Chàra Rose
  category: Games
  description:
    en_us: Crafty is an open source Minecraft control panel built using Tornado and AdminLTE, featuring server scheduling, a interactive console and the ability to run almost any type of Minecraft server
    es_es: Crafty es un panel de control de Minecraft de código abierto creado con Tornado y AdminLTE, que incluye programación de servidores, una consola interactiva y la capacidad de ejecutar casi cualquier tipo de servidor de Minecraft.
    zh_cn: Crafty是一个使用Tornado和AdminLTE构建的开源Minecraft控制面板，具有服务器调度、交互式控制台和运行几乎任何类型的Minecraft服务器的功能。
  developer: Crafty Team
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Crafty/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Crafty/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Crafty/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Crafty/screenshot-3.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Crafty/screenshot-4.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Crafty/screenshot-5.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Crafty/screenshot-6.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Crafty/screenshot-7.png
  tagline:
    en_us: Take control of your Minecraft servers.
    es_es: Toma el control de tus servidores de Minecraft.
    zh_cn: 掌控你的Minecraft服务器。
  tips:
    before_install:
      ar_sa: |
        الحساب الافتراضي

        | اسم المستخدم | كلمة المرور |
        |----------|----------|
        | `admin`    | `app/config/default-creds.txt` |
      de_de: |
        Standardkonto
        | Benutzername | Passwort |
        |----------|----------|
        | `admin`    | `app/config/default-creds.txt` |
      en_us: |
        Default Account
        | Username | Password |
        |----------|----------|
        | `admin`    | `app/config/default-creds.txt` |
      es_es: |
        Cuenta predeterminada
        | Nombre de usuario | Contraseña |
        |----------|----------|
        | `admin`    | `app/config/default-creds.txt` |
      fr_fr: |
        Compte par défaut
        | Nom d'utilisateur | Mot de passe |
        |----------|----------|
        | `admin`    | `app/config/default-creds.txt` |
      hu_hu: |
        Alapértelmezett fiók
        | Felhasználónév | Jelszó |
        |----------|----------|
        | `admin`    | `app/config/default-creds.txt` |
      it_it: |
        Account predefinito
        | Nome utente | Password |
        |----------|----------|
        | `admin`    | `app/config/default-creds.txt` |
      pl_pl: |
        Konto domyślne
        | Nazwa użytkownika | Hasło |
        |----------|----------|
        | `admin`    | `app/config/default-creds.txt` |
      pt_br: |
        Conta padrão
        | Nome de usuário | Senha |
        |----------|----------|
        | `admin`    | `app/config/default-creds.txt` |
      ru_ru: |
        Учетная запись по умолчанию
        | Имя пользователя | Пароль |
        |----------|----------|
        | `admin`    | `app/config/default-creds.txt` |
      sv_se: |
        Standardkonto
        | Användarnamn | Lösenord |
        |----------|----------|
        | `admin`    | `app/config/default-creds.txt` |
      uk_ua: |
        Обліковий запис за замовчуванням
        | Ім'я користувача | Пароль |
        |----------|----------|
        | `admin`    | `app/config/default-creds.txt` |
      zh_cn: |
        默认账号
        | 用户名 | 密码 |
        |----------|----------|
        | `admin`    | `app/config/default-creds.txt` |
  title:
    en_us: Crafty
  index: /panel
  scheme: https
  port_map: "8111"
