name: crafty
# Base file from https://gitlab.com/crafty-controller/crafty-4/-/blob/dev/docker/docker-compose.yml
version: '3'

services:
  crafty:
    container_name: crafty-container
    image: registry.gitlab.com/crafty-controller/crafty-4:4.1.3
    restart: always
    environment:
      - TZ=Etc/UTC
    ports:
      - "8110:8000" # HTTP
      - "8111:8443" # HTTPS
      - "8112:8123" # DYNMAP
      - "19132:19132/udp" # BEDROCK
      - "25500-25600:25500-25600" # MC SERVER PORT RANGE
    volumes:
      - /DATA/AppData/crafty/backups:/crafty/backups
      - /DATA/AppData/crafty/logs:/crafty/logs
      - /DATA/AppData/crafty/servers:/crafty/servers
      - /DATA/AppData/crafty/config:/crafty/app/config
      - /DATA/AppData/crafty/import:/crafty/import

    x-casaos:
      ports:
        - container: "8000"
          description:
            en_us: WebUI HTTP Port
          protocol: tcp

        - container: "19132"
          description:
            en_us: Minecraft Bedrock listening Port (UDP)
          protocol: udp

        - container: "25565"
          description:
            en_us: Minecraft listening Port (TCP)
          protocol: tcp

        - container: "25566"
          description:
            en_us: Minecraft listening Port (TCP)
          protocol: tcp

        - container: "25567"
          description:
            en_us: Minecraft listening Port (TCP)
          protocol: tcp

        - container: "25568"
          description:
            en_us: Minecraft listening Port (TCP)
          protocol: tcp

        - container: "25569"
          description:
            en_us: Minecraft listening Port (TCP)
          protocol: tcp

        - container: "25570"
          description:
            en_us: Minecraft listening Port (TCP)
          protocol: tcp

        - container: "25565"
          description:
            en_us: Minecraft listening Port (UDP)
          protocol: udp

        - container: "25566"
          description:
            en_us: Minecraft listening Port (UDP)
          protocol: udp

        - container: "25567"
          description:
            en_us: Minecraft listening Port (UDP)
          protocol: udp

        - container: "25568"
          description:
            en_us: Minecraft listening Port (UDP)
          protocol: udp

        - container: "25569"
          description:
            en_us: Minecraft listening Port (UDP)
          protocol: udp

        - container: "25570"
          description:
            en_us: Minecraft listening Port (UDP)
          protocol: udp
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: crafty
  author: Chàra Rose
  category: Games
  description:
    en_us: Crafty is an open source Minecraft control panel built using Tornado and AdminLTE, featuring server scheduling, a interactive console and the ability to run almost any type of Minecraft server 
    es_es: Crafty es un panel de control de Minecraft de código abierto creado con Tornado y AdminLTE, que incluye programación de servidores, una consola interactiva y la capacidad de ejecutar casi cualquier tipo de servidor de Minecraft.
  developer: Crafty Team
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Crafty/icon.png
  tagline:
    en_us: Take control of your Minecraft servers.
    es_es: Toma el control de tus servidores de Minecraft.
  tips:
    before_install:
      ar_sa: |
        الحساب الافتراضي

        | اسم المستخدم | كلمة المرور |
        |----------|----------|
        | `admin`    | `crafty` |
      de_de: |
        Standardkonto

        | Benutzername | Passwort |
        |----------|----------|
        | `admin`    | `crafty` |
      en_us: |
        Default Account

        | Username | Password |
        |----------|----------|
        | `admin`    | `crafty` |
      es_es: |
        Cuenta predeterminada

        | Nombre de usuario | Contraseña |
        |----------|----------|
        | `admin`    | `crafty` |
      fr_fr: |
        Compte par défaut

        | Nom d'utilisateur | Mot de passe |
        |----------|----------|
        | `admin`    | `crafty` |
      hu_hu: |
        Alapértelmezett fiók

        | Felhasználónév | Jelszó |
        |----------|----------|
        | `admin`    | `crafty` |
      it_it: |
        Account predefinito

        | Nome utente | Password |
        |----------|----------|
        | `admin`    | `crafty` |
      pl_pl: |
        Konto domyślne

        | Nazwa użytkownika | Hasło |
        |----------|----------|
        | `admin`    | `crafty` |
      pt_br: |
        Conta padrão

        | Nome de usuário | Senha |
        |----------|----------|
        | `admin`    | `crafty` |
      ru_ru: |
        Учетная запись по умолчанию

        | Имя пользователя | Пароль |
        |----------|----------|
        | `admin`    | `crafty` |
      sv_se: |
        Standardkonto

        | Användarnamn | Lösenord |
        |----------|----------|
        | `admin`    | `crafty` |
      uk_ua: |
        Обліковий запис за замовчуванням

        | Ім'я користувача | Пароль |
        |----------|----------|
        | `admin`    | `crafty` |
      zh_cn: |
        默认账号

        | 用户名 | 密码 |
        |----------|----------|
        | `admin`    | `crafty` |
  title:
    en_us: Crafty
  index: /panel
  scheme: https
  port_map: "8111"