name: siyuan-note
services:
  siyuan-note:
    command:
      --accessAuthCode=casaos
      --workspace=/siyuan/workspace/
    environment:
      PUID: "1000"
      PGID: "1000"
    image: b3log/siyuan:v3.0.1
    deploy:
      resources:
        reservations:
          memory: "512M"
    network_mode: bridge
    ports:
      - target: 6806
        published: "6806"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/workspace
        target: /siyuan/workspace
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: TimeZone
            zh_cn: 时区
        - container: accessAuthCode
          description:
            en_us: Access authorization code, please be sure to modify, otherwise anyone can read and write your data
            zh_cn: 访问码，请修改，否则其他人可以直接访问并修改你的数据
      ports:
        - container: "6806"
          description:
            en_us: WebUI HTTP Port
            zh_cn: WebUI HTTP 端口
      command:
        - workspace:
            en_us: specifies the workspace folder path, mounted to the container via -v on the host
            zh_cn: 指定工作区文件夹路径，通过主机上的 -v 装载到容器
      volumes:
        - container: /siyuan/workspace
          description:
            en_us: siyuan-note workspace.
            zh_cn: 思源笔记默认工作区
    container_name: siyuan-note
x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: siyuan-note
  author: CasaOS Team
  category: Notes
  description:
    en_us: SiYuan is a privacy-first personal knowledge management system, support fine-grained block-level reference and Markdown WYSIWYG.
    zh_cn: 思源笔记是一款隐私优先的个人知识管理系统，支持完全离线使用，同时也支持端到端加密同步。
  tagline:
    en_us: Personal knowledge management system
    zh_cn: 个人知识管理系统
  developer: siyuan-note
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Siyuan-Note/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Siyuan-Note/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Siyuan-Note/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Siyuan-Note/screenshot-3.jpg
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Siyuan-Note/thumbnail.png
  tips:
    before_install:
      en_us: |
        | accessAuthCode |
        | -------- |
        | `casaos`    |
      zh_cn: |
        | 访问码 |
        | -------- |
        | `casaos`    |
  title:
    en_us: SiYuan Note
    zh_cn: 思源笔记
  index:
  port_map: "6806"
