name: filebrowser
services:
  filebrowser:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
    image: filebrowser/filebrowser:v2.23.0
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 80
        published: "80"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/db
        target: /db
      - type: bind
        source: /DATA
        target: /srv
    x-casaos:
      author: CasaOS Team
      category: Cloud
      container:
        envs:
          -
            container: TZ
            description:
              en_US: TimeZone
          -
            container: PUID
            description:
              en_US: Run FileBrowser as specified uid.
          -
            container: PGID
            description:
              en_US: Run FileBrowser as specified gid.
        index: /
        port_map: "80"
        ports:
          -
            container: "80"
            description:
              en_US: WebUI Port

        shell: sh
        volumes:
          -
            container: /db
            description:
              en_US: FileBrowser database directory.
          -
            container: /srv
            description:
              en_US: FileBrowser managed directory.
      description:
        en_US: File Browser - Webbased File Browser including sharing functions etc.
      developer: File Browser
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/FileBrowser/icon.png
      screenshot_link:
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/FileBrowser/screenshot-1.jpg
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/FileBrowser/screenshot-2.jpg
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/FileBrowser/screenshot-3.jpg
      tagline:
        en_US: Upload, delete, preview, rename, edit and share your files.
      thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/FileBrowser/thumbnail.jpg
      tips:
        before_install:
          - content:
              en_US: Default Account
          - content:
              en_US: 'Username: '
            value: admin
          - content:
              en_US: 'Password: '
            value: admin
      title:
        en_US: FileBrowser
x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main_app: filebrowser
