name: esphome
services:
  esphome:
    container_name: esphome
    deploy:
      resources:
        reservations:
          memory: 512M
    image: ghcr.io/esphome/esphome:2025.2
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/ESPHome/icon.png
    restart: always
    ports:
      - target: 6052
        published: "6052"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    environment:
      ESPHOME_DASHBOARD_USE_PING: "false"
      TZ: $TZ
    network_mode: host
    privileged: false
    x-casaos:
      envs:
        - container: ESPHOME_DASHBOARD_USE_PING
          description:
            en_us: Ping IP addresses instead of mDNS
            zh_cn: Ping IP 地址而不是 mDNS
        - container: TZ
          description:
            en_us: TimeZone
            zh_cn: 时区
      volumes:
        - container: /config
          description:
            en_us: AppData Path Config File
            zh_cn: AppData路径配置文件
      ports:
        - container: '6052'
          description:
            en_us: WebUI Port for ESPHome
            zh_cn: ESPHome 的 WebUI 端口
x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  author: kd9lsv
  category: "Home Automation"
  description:
    en_us: ESPHome is a system to control your microcontrollers by simple yet powerful configuration files and control them remotely through Home Automation systems.
    zh_cn: ESPHome 是一个通过简单而强大的配置文件控制微控制器并通过家庭自动化系统远程控制它们的系统。
  tagline:
    en_us: Home Automation systems
    zh_cn: 家庭自动化系统
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/ESPHome/icon.png
  index: /
  main: esphome
  port_map: "6052"
  scheme: http
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/ESPHome/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/ESPHome/screenshot-2.png
  store_app_id: esphome
  title:
    en_us: ESPHome
