name: lucky
services:
  lucky:
    deploy:
      resources:
        reservations:
          memory: 64M
    image: gdy666/lucky:2.9.0
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/lucky
        target: /goodluck
    environment:
      TZ: $TZ
    network_mode: host
    privileged: false
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: lucky
  author: IceWhaleTech
  category: Network
  description:
    en_us: A powerful tool for port forwarding, reverse proxy, dynamic DNS, wake-on-LAN, IPv4 NAT traversal, webdav services, task scheduling, and automatic certificate management.
    zh_cn: 一款功能强大的端口转发、反向代理、动态域名、网络唤醒、IPv4内网穿透、webdav服务、计划任务和自动证书管理工具。
  developer: gdy666
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Lucky/icon.png
  index: /
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Lucky/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Lucky/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Lucky/screenshot-3.png
  tagline:
    en_us: Powerful networking tool
    zh_cn: 家用软硬路由公网利器
  tips:
    before_install:
      en_us: Default login account `666`, Default login password `666`,tips:`Before each update, remember to back up the configuration`.
      zh_cn: 默认登录账号 `666`，默认登录密码 `666`,提示：`每次更新前，请记得备份好配置`
  title:
    en_us: Lucky
  port_map: "16601"
  scheme: http
  store_app_id: lucky
