name: build documentation and publish

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: remove all file except icon.png
        run: find . -type f -not \( -name 'icon.png' -or -name '*.json' -or -name '*.yml' \) -delete
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB2 }}
        with:
          source-directory: './Apps'
          destination-github-username: 'IceWhaleTech'
          destination-repository-name: 'CasaOS-NewAppStore'
          user-email: q2676515970@163.com
          target-directory: './Apps'
      - name: Copycat
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB2 }}
          src_path: ./recommend-list.json
          dst_owner: IceWhaleTech
          dst_repo_name: CasaOS-NewAppStore
          email: q2676515970@163.com
          src_branch: main
          dst_branch: main
