name: build documentation and publish

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: remove all file except icon.png
        run: find . -type f -not \( -name 'icon.png' -or -name '*.json' -or -name '*.yml' \) -delete
      - name: remove .github
        run: |
          rm -fr ./github
          rm -fr ./build
          rm -fr ./help
          rm ./.gitignore
          rm ./CONTRIBUTING.md
          rm ./README.md
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB2 }}
        with:
          source-directory: '.'
          destination-github-username: 'IceWhaleTech'
          destination-repository-name: 'CasaOS-NewAppStore'
          user-email: q2676515970@163.com
          target-directory: ''
