name: release

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: remove all screenshots
        run: find . -name "screenshot*" | xargs rm -f
      - name: remove all thumbnails
        run: find . -name "thumbnail*" | xargs rm -f
      - name: create a build with sysroot
        id: build
        run: |
          mkdir -p /tmp/build/sysroot/var/lib/casaos/appstore/default.new
          cp -rv * /tmp/build/sysroot/var/lib/casaos/appstore/default.new
          pushd /tmp
          tar zcvf linux-all-appstore-${{ github.ref_name }}.tar.gz build
      - uses: softprops/action-gh-release@v1
        if: steps.build.outcome == 'success'
        with:
          files: /tmp/linux-all-appstore-${{ github.ref_name }}.tar.gz
          draft: true
          prerelease: true
          fail_on_unmatched_files: true
