name: gitea
services:
  gitea:
    environment:
      USER_GID: "1000"
      USER_UID: "1000"
    image: gitea/gitea:1.22.4
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge
    ports:
      - target: 3000
        published: "3002"
        protocol: tcp
      - target: 22
        published: "222"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /data
    x-casaos:
      envs:
        - container: USER_UID
          description:
            en_us: The UID (Unix user ID) of the user that runs Gitea
            zh_cn: Gitea 运行的用户的 UID（Unix 用户 ID）
        - container: USER_GID
          description:
            en_us: The GID (Unix group ID) of the user that runs Gitea
            zh_cn: Gitea 运行的用户的 GID（Unix 组 ID）
      ports:
        - container: "3000"
          description:
            en_us: WebUI Port
            zh_cn: WebUI 端口

        - container: "22"
          description:
            en_us: SSH Port
            zh_cn: SSH 端口

      volumes:
        - container: /data
          description:
            en_us: Gitea data directory.
            zh_cn: Gitea 数据目录。
    container_name: gitea
x-casaos:
  architectures:
    - amd64
    - arm64
  main: gitea
  author: CasaOS Team
  category: Developer
  description:
    en_us: |
      Gitea is a painless self-hosted all-in-one software development service, it includes Git hosting, code review, team collaboration, package registry and CI/CD. It is similar to GitHub, Bitbucket and GitLab. 
      
      - Code Hosting
      Gitea supports creating and managing repositories, browsing commit history and code files, reviewing and merging code submissions, managing collaborators, handling branches, and more. It also supports many common Git features such as tags, Cherry-pick, hooks, integrated collaboration tools, and more.
      
      - Lightweight and Fast
      One of Gitea's design goals is to be lightweight and fast in response. Unlike some large code hosting platforms, it remains lean, performing well in terms of speed, and is suitable for resource-limited server environments. Due to its lightweight design, Gitea has relatively low resource consumption and performs well in resource-constrained environments.
      
      - Easy Deployment and Maintenance
      It can be easily deployed on various servers without complex configurations or dependencies. This makes it convenient for individual developers or small teams to set up and manage their own Git services.
      
      - Security
      Gitea places a strong emphasis on security, offering features such as user permission management, access control lists, and more to ensure the security of code and data.
      
      - Code Review
      Code review supports both the Pull Request workflow and AGit workflow. Reviewers can browse code online and provide review comments or feedback. Submitters can receive review comments and respond or modify code online. Code reviews can help individuals and organizations enhance code quality.
      
      - CI/CD
      Gitea Actions supports CI/CD functionality, compatible with GitHub Actions. Users can write workflows in familiar YAML format and reuse a variety of existing Actions plugins. Actions plugins support downloading from any Git website.
      
      - Project Management
      Gitea tracks project requirements, features, and bugs through columns and issues. Issues support features like branches, tags, milestones, assignments, time tracking, due dates, dependencies, and more.
      
      - Artifact Repository
      Gitea supports over 20 different types of public or private software package management, including Cargo, Chef, Composer, Conan, Conda, Container, Helm, Maven, npm, NuGet, Pub, PyPI, RubyGems, Vagrant, and more.
      
      - Open Source Community Support
      Gitea is an open-source project based on the MIT license. It has an active open-source community that continuously develops and improves the platform. The project also actively welcomes community contributions, ensuring updates and innovation.
      
      - Multilingual Support
      Gitea provides interfaces in multiple languages, catering to users globally and promoting internationalization and localization.
    zh_cn: |
      Gitea 是一个轻松自托管的全方位软件开发服务，包含 Git 托管、代码评审、团队协作、包注册表和 CI/CD。它类似于 GitHub、Bitbucket 和 GitLab。

      - 代码托管
      Gitea 支持创建和管理仓库、浏览提交历史和代码文件、评审和合并代码提交、管理协作者、处理分支等。它还支持许多常见的 Git 功能，如标签、Cherry-pick、钩子、集成协作工具等。

      - 轻量且快速
      Gitea 的设计目标之一是轻量且响应迅速。与一些大型代码托管平台不同，它保持精简，在速度方面表现良好，适合资源有限的服务器环境。由于其轻量设计，Gitea 的资源消耗相对较低，在资源受限的环境中表现出色。

      - 易于部署和维护
      Gitea 可以轻松部署在各种服务器上，无需复杂的配置或依赖项。这使得个人开发者或小团队可以方便地设置和管理自己的 Git 服务。

      - 安全性
      Gitea 非常重视安全性，提供了用户权限管理、访问控制列表等功能，以确保代码和数据的安全。

      - 代码评审
      Gitea 的代码评审支持 Pull Request 工作流和 AGit 工作流。评审者可以在线浏览代码并提供评审意见或反馈。提交者可以接收评审意见并在线回应或修改代码。代码评审有助于个人和组织提升代码质量。

      - CI/CD
      Gitea Actions 支持 CI/CD 功能，兼容 GitHub Actions。用户可以使用熟悉的 YAML 格式编写工作流，并重用各种现有的 Actions 插件。Actions 插件支持从任何 Git 网站下载。

      - 项目管理
      Gitea 通过列和问题跟踪项目需求、功能和 bug。问题支持分支、标签、里程碑、分配、时间跟踪、截止日期、依赖关系等功能。

      - 工件仓库
      Gitea 支持超过 20 种不同类型的公共或私有软件包管理，包括 Cargo、Chef、Composer、Conan、Conda、Container、Helm、Maven、npm、NuGet、Pub、PyPI、RubyGems、Vagrant 等。

      - 开源社区支持
      Gitea 是基于 MIT 许可证的开源项目。它拥有一个活跃的开源社区，持续开发和改进平台。该项目还积极欢迎社区贡献，确保更新和创新。

      - 多语言支持
      Gitea 提供多语言界面，满足全球用户需求，促进国际化和本地化。
    ar_sa: Gitea هو حل استضافة الشفرة الخفيفة المدار من قبل المجتمع مكتوب بلغة Go.
    de_de: Gitea ist eine von der Community verwaltete, leichte Code-Hosting-Lösung, die in Go geschrieben ist.
    es_es: Gitea es una solución de alojamiento de código ligera administrada por la comunidad escrita en Go.
    fr_fr: Gitea est une solution d'hébergement de code légère gérée par la communauté écrite en Go.
    hu_hu: A Gitea egy közösség által kezelt könnyű kódhelyezési megoldás, amelyet Go írt.
    it_it: Gitea è una soluzione di hosting di codice leggera gestita dalla comunità scritta in Go.
    ru_ru: Gitea - это легкое решение для размещения кода, управляемое сообществом, написанное на Go.
    pl_pl: Gitea to lekka rozwiązanie do hostingu kodu zarządzane przez społeczność napisane w Go.
    pt_br: O Gitea é uma solução de hospedagem de código leve gerenciada pela comunidade escrita em Go.
    sv_se: Gitea är ett communityhanterat lätthanterat kodhostningslösning skrivet i Go.
    uk_ua: Gitea - це легке рішення для розміщення коду, кероване спільнотою, написане на Go.
  developer: Gitea
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Gitea/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Gitea/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Gitea/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Gitea/screenshot-3.png
  tagline:
    en_us: Self-hosted software development service
    zh_cn: 自托管软件开发服务
    ar_sa: Git مع كوب من الشاي
    de_de: Git mit einem Tässchen Tee
    es_es: Git con una taza de té
    fr_fr: Git avec une tasse de thé
    hu_hu: Git egy csésze tea kíséretében
    it_it: Git con una tazza di tè
    ru_ru: Git с чашечкой чая
    pl_pl: Git z filiżanką herbaty
    pt_br: Git com uma xícara de chá
    sv_se: Git med en kopp te
    uk_ua: Git з чашкою чаю
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Gitea/thumbnail.png
  tips:
    before_install:
      en_us: |
        When the App is installed, the first account registered will become the administrator account.
      zh_cn: |
        安装应用后，注册的第一个账号将成为管理员账号。
  title:
    en_us: Gitea
  index: /
  port_map: "3002"
